backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "President", name: president, widget: object, fields: [
              {label: "Quote", name: "quote", widget: "string"},
              {label: "Author", name: "author", widget: "string"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/sponsors/_index.md"
        label: "Sponsors Page"
        name: "sponsors"
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: text}
          - label: Sponsors
            name: sponsors
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Link, name: link, widget: string}
      - file: "site/content/about/_index.md"
        label: "About Us Page"
        name: "about"
        editor:
          - preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: About
            name: about
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
              - {label: "Associated Quote", name: quote_wrapper, widget: object, fields: [
                  {label: "Quote", name: "quote", widget: "string"},
                  {label: "Author", name: "author", widget: "string"}]}
          - label: Grounds
            name: grounds
            widget: object
            fields:
                - {label: "Heading", name: heading, widget: string}
                - {label: "Text", name: text, widget: text}
      - file: "site/content/practical-information/_index.md"
        label: "Information Page"
        name: "practical-information"
        editor:
            - preview: false
        fields:
            - {label: Title, name: title, widget: string}
            - {label: Image, name: image, widget: image}
            - label: Information
              name: information
              widget: list
              fields:
                - {label: Heading, name: heading, widget: string}
                - {label: Text, name: text, widget: text}

